import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <div className='container'>
          <nav className='nav'>
            <div className='logo'>
              <img src='./images/logo.svg' alt='logo' />
              <p>Boldo</p>
            </div>
            <ul>
              <li>
                <a href='/'>Products</a>
              </li>
              <li>
                <a href='/'>Services</a>
              </li>
              <li>
                <a href='/'>About</a>
              </li>
              <li>
                <a className='loginBtn button-primary ' href='/'>
                  Log In
                </a>
              </li>
            </ul>
          </nav>

          <div className='thoughts'>
            <p>Blog</p>
            <h1>Thoughts and words</h1>
          </div>

          {/*headline section*/}
          <section className='headline' aria-label='headline story'>
            <div className='housesImg'>
              <img src='./images/houses.svg' alt='houses' />
            </div>
            <article className='headlineRight'>
              <div className='details'>
                <span className='blue'>Category</span>
                <span className='date'>November 22, 2021</span>
              </div>
              <p className='headlineText'>Pitch termsheet backing validation focus release.</p>
              <div className='details'>
                <img src='./images/bing.svg' alt='person' />
                <span>Chandler Bing</span>
              </div>
            </article>
          </section>
          <hr />

          {/*articles section*/}
          <section aria-label='latest' className='latest'>
            <h2>Latest News</h2>
            <div className='postsGrid'>
              <a href='/' className='postItem'>
                <img src='./images/post1.svg' alt='post' />
                <div className='details'>
                  <span className='blue '>Category</span>
                  <span className='date'>November 22, 2021</span>
                </div>
                <p>Pitch termsheet backing validation focus release.</p>
                <div className='details'>
                  <img src='./images/bing.svg' alt='person' />
                  <span>Chandler Bing</span>
                </div>
              </a>
              <a href='/' className='postItem'>
                <img src='./images/post2.svg' alt='post' />
                <div className='details'>
                  <span className='blue '>Category</span>
                  <span className='date'>November 22, 2021</span>
                </div>
                <p>Seed round direct mailing non-disclosure agreement graphical user interface rockstar.</p>
                <div className='details'>
                  <img src='./images/rachel.svg' alt='person' />
                  <span>Rachel Green</span>
                </div>
              </a>
              <a href='/' className='postItem'>
                <img src='./images/post3.svg' alt='post' />
                <div className='details'>
                  <span className='blue '>Category</span>
                  <span className='date'>November 22, 2021</span>
                </div>
                <p>Beta prototype sales iPad gen-z marketing network effects value proposition.</p>
                <div className='details'>
                  <img src='./images/monica.svg' alt='person' />
                  <span>Monica Geller</span>
                </div>
              </a>
              <a href='/' className='postItem'>
                <img src='./images/post4.svg' alt='post' />
                <div className='details'>
                  <span className='blue '>Category</span>
                  <span className='date'>November 22, 2021</span>
                </div>
                <p>Pitch termsheet backing validation focus release.</p>
                <div className='details'>
                  <img src='./images/bing.svg' alt='person' />
                  <span>Chandler Bing</span>
                </div>
              </a>
              <a href='/' className='postItem'>
                <img src='./images/post5.svg' alt='post' />
                <div className='details'>
                  <span className='blue '>Category</span>
                  <span className='date'>November 22, 2021</span>
                </div>
                <p>Seed round direct mailing non-disclosure agreement graphical user interface rockstar.</p>
                <div className='details'>
                  <img src='./images/rachel.svg' alt='person' />
                  <span>Rachel Green</span>
                </div>
              </a>
              <a href='/' className='postItem'>
                <img src='./images/post6.svg' alt='post' />
                <div className='details'>
                  <span className='blue '>Category</span>
                  <span className='date'>November 22, 2021</span>
                </div>
                <p>Beta prototype sales iPad gen-z marketing network effects value proposition.</p>
                <div className='details'>
                  <img src='./images/monica.svg' alt='person' />
                  <span>Monica Geller</span>
                </div>
              </a>
            </div>
            <button className='loadMore blue button-primary'>Load more</button>
          </section>

          {/*cta banner section*/}
          <section className='cta' aria-label='cta banner'>
            <div className='ctaWrapper'>
              <h3 className='ctaText'>An enterprise template to ramp up your company website</h3>
              <form>
                <input type='email' placeholder='Your email address' />
                <button>Start now</button>
              </form>
            </div>
          </section>

          {/*footer section*/}
          <footer>
            <div className='footerLeft'>
              <div className='logo'>
                <img src='./images/logo.svg' alt='logo' />
                <p>Boldo</p>
              </div>
              <p className='date'>
                Social media validation business model canvas graphical user interface launch party creative facebook iPad twitter.
              </p>
              <p className='date'>All rights reserved.</p>
            </div>
            <div className='footerRight'>
              <dl>
                <dt>Landings</dt>
                <dd className='date'>
                  <a href=''>Products</a>
                </dd>
                <dd className='date'>
                  <a href=''>Home</a>
                </dd>
                <dd className='date'>
                  <a href=''>Services</a>
                </dd>
              </dl>
              <dl>
                <dt>Company</dt>
                <dd className='date'>
                  <a href=''>Home</a>
                </dd>
                <dd className='date'>
                  <a href=''>Career </a>
                  <span className='hiringBadge'>Hiring!</span>
                </dd>
                <dd className='date'>
                  <a href=''>Services</a>
                </dd>
              </dl>
              <dl>
                <dt>Resources</dt>
                <dd className='date'>
                  <a href=''>Blog</a>
                </dd>
                <dd className='date'>
                  <a href=''>Products</a>
                </dd>
                <dd className='date'>
                  <a href=''>Services</a>
                </dd>
              </dl>
            </div>
          </footer>
        </div>
      </div>
    </>
  );
}
